# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IFOZ4e3TC9GzsXwAqdlBaGyQTSLtuPC7kutR9tRYh+EBe2RZhmrCPtqxSANgystcP/wyPR5x6ceuX1LrTl51yDIvo2WbCTSSnjIwh21F/DH7KdxMm0o3/LSoWzC7zO84komFvyE8CCAOt9kVW+UP3s/SmibHy7uWbyVbg9kR1Rxt5q0UZjG/+xYFmIHbkjMRXhRmz5JLzIAzAmMUYkOv2FqbKqM2FcTwZRk0Xuu/BsfHS/3gU91urXKjgqTcKgdvFBh2fni/roh8WWfkVfYLKSHmKu3i9vwrsooauVlX5GGNrkeejitW4KqsBEboROGMh2tenV7CnmPuan6lC4AA+Ni8Y9dWDe1EMZ0BcciVsFHTLv/YWw595IfKggrGGs5q0qFIqLCFt4S4NSWcd4hKVg6hjXP6nmDZocHLDIWsSydKno/SAE+n6I3WWV7vwJkdMIQSfgIW3+55YDmFynXRBQZ5LB4l+4ExZurVG7oQ9hLJXE0smgA/vHVpGlxibI+qTza1OBYXsVvyo+ES2ggF1KbcUeETEbOlzsEAuU7cFjtxKJn8F6d/f36I1/lNmKTiAIRBjOq2nJp0iPDeMR5aB8buLhLTfPHTZCWXPw7wZmgWtzNqrXeEF0pZDaRyz3ZFXQ+KI5Deh3H7l5VUgekBim+5wqM7W8dCqmueGLGZLEo="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
