travis:
  secure:
    BINSTAR_TOKEN: IFOZ4e3TC9GzsXwAqdlBaGyQTSLtuPC7kutR9tRYh+EBe2RZhmrCPtqxSANgystcP/wyPR5x6ceuX1LrTl51yDIvo2WbCTSSnjIwh21F/DH7KdxMm0o3/LSoWzC7zO84komFvyE8CCAOt9kVW+UP3s/SmibHy7uWbyVbg9kR1Rxt5q0UZjG/+xYFmIHbkjMRXhRmz5JLzIAzAmMUYkOv2FqbKqM2FcTwZRk0Xuu/BsfHS/3gU91urXKjgqTcKgdvFBh2fni/roh8WWfkVfYLKSHmKu3i9vwrsooauVlX5GGNrkeejitW4KqsBEboROGMh2tenV7CnmPuan6lC4AA+Ni8Y9dWDe1EMZ0BcciVsFHTLv/YWw595IfKggrGGs5q0qFIqLCFt4S4NSWcd4hKVg6hjXP6nmDZocHLDIWsSydKno/SAE+n6I3WWV7vwJkdMIQSfgIW3+55YDmFynXRBQZ5LB4l+4ExZurVG7oQ9hLJXE0smgA/vHVpGlxibI+qTza1OBYXsVvyo+ES2ggF1KbcUeETEbOlzsEAuU7cFjtxKJn8F6d/f36I1/lNmKTiAIRBjOq2nJp0iPDeMR5aB8buLhLTfPHTZCWXPw7wZmgWtzNqrXeEF0pZDaRyz3ZFXQ+KI5Deh3H7l5VUgekBim+5wqM7W8dCqmueGLGZLEo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
